### ISSUE TITLE
Ignore/Listen message response in Direct Messages

### ISSUE THREAD

**Issue by nindoja** [tessellator/lita-ignore-me#2]
Can the bot respond via direct message to the user instead of in the channel?  This would minimize the traffic in the channel.

**Comment by tessellator** [comment]
This is a good idea. I'll look into it.

**Comment by tessellator** [comment]
So as I spent time thinking about this yesterday, I realized that if I implemented exactly what you asked, it might come across as action at a distance. With the pull request I've opened, I'm trying to strike a compromise: the robot will respond to you in whatever room you speak to it, but you can now specify which room to which the new rule should be applied (e.g., `ignore me in #some-channel`).

In the case of Slack (which is my primary target), this means that you can send a private message to the robot, and it will respond to you in that private channel. People can opt to not clutter public channels with bot responses, though I don't think that's really going to be a big problem long-term.

Does this seem fair, @nindoja? What do you think, @iamvery?

**Comment by nindoja** [comment]
I think that will be fine.

**Comment by tessellator** [comment]
Sounds good!
